"""
Game state module.

Provides GameState class to bundle together information about player, world,
and various other game data.
"""


class GameState():
    """ A container with all game information. """

    def __init__(self):
        self.data = None
        self.player = None
        self.world = None
        self.turn = 0


class GameStateFromData(GameState):
    """ A container with all game information, derived from saved files. """

    def __init__(self, data):
        super().__init__()
        raise NotImplementedError


class GameStateFromScratch(GameState):
    """
    A container with all game information, derived from pieces generated by the
    game in response to user's actions.
    """

    def __init__(self, data, player, world):
        super().__init__()
        self.data = data
        self.player = player
        self.world = world
        self.turn = 0
